# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
