# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20170602_1114'),
        ('health', '0002_auto_20170430_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=255)),
                ('limit', models.IntegerField()),
                ('timing', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('comment', models.TextField()),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Blank')),
                ('dose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health.Dose')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Medication')),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
