# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20170602_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('results', models.TextField()),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Blank')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fullname', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('hospital_name', models.CharField(max_length=255)),
                ('blank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health.Blank')),
            ],
        ),
    ]
