# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_examination_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='final_diagnosis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blank',
            name='prov_diagnosis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
