# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20170603_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='to_date',
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
