# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20170426_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('middlename', models.CharField(max_length=255, null=True)),
                ('bio', models.TextField(max_length=1000)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=255)),
                ('experience', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_from', models.DateField()),
                ('data_to', models.DateField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='PatientProfile',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Education'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospitals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Hospital'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='procedures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Procedure'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Specialization'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
