# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170430_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
