# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170430_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
