# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20170430_0922'),
        ('users', '0012_auto_20170430_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospitals',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospitals',
            field=models.ManyToManyField(to='health.Hospital'),
        ),
    ]
