# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170430_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='procedures',
        ),
        migrations.AddField(
            model_name='specialization',
            name='procedures',
            field=models.ManyToManyField(related_name='procedures', to='users.Procedure'),
        ),
    ]
