# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170430_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='doctor_profile',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Education'),
        ),
    ]
