# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Specialization'),
        ),
    ]
