# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_hospitalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Courses'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Employment'),
        ),
    ]
