# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
