# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20170513_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='doctor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile_id', to='users.DoctorProfile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile_id', to='users.PatientProfile'),
        ),
    ]
