# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20170513_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_from',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_to',
        ),
    ]
