# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
