# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20170520_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='employment',
        ),
        migrations.AddField(
            model_name='courses',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DoctorProfile'),
        ),
        migrations.AddField(
            model_name='employment',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DoctorProfile'),
        ),
    ]
