# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20170520_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='data_from',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='data_to',
            new_name='date_to',
        ),
    ]
