# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20170521_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attentiveness', models.FloatField()),
                ('qualification', models.FloatField()),
                ('quality', models.FloatField()),
                ('qualityToPrice', models.FloatField()),
                ('recommendation', models.BooleanField()),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DoctorProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PatientProfile'),
        ),
    ]
