# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20170531_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
