# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20170531_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DoctorProfile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PatientProfile'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospitals',
            field=models.ManyToManyField(to='users.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalprice',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Hospital'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Hospital'),
        ),
    ]
