# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20170602_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Hospital'),
        ),
    ]
