# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_notification_visit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_number',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
