# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_appointment_visit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='qualityToPrice',
        ),
        migrations.AddField(
            model_name='feedback',
            name='quality_to_price',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attentiveness',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='qualification',
            field=models.FloatField(max_length=5),
        ),
    ]
